### ISSUE TITLE
Unable to process JSON file when watching a folder

### ISSUE THREAD

**Issue by mattplindsay** [annot8/annot8-components#43]
I have the following setup:

- Annot8-Components built from source from Master at commit 24b3ac6
- Baleen3 v3.0.2
- Running in Docker container (built from Ubuntu:latest) using a docker-compose generated Volume (and /workspace)
- The pipeline has a simple annot8 File System Source leading into an annot8 JSON File Extractor (then into an annot8 email extractor).

Symptoms
If I start up the Pipeline after the file has been added, it prcessess correctly
If I add a new .json file into the folder being monitored, It does not prcess correctly and throws the following error:

`  items.json
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
    at java.nio.file.Files.newByteChannel(Files.java:371)
    at java.nio.file.Files.newByteChannel(Files.java:422)
    at java.nio.file.Files.readAllBytes(Files.java:3206)
    at java.nio.file.Files.readString(Files.java:3284)
    at io.annot8.components.files.processors.JsonExtractor$Processor.processJson(JsonExtractor.java:108)
    at io.annot8.components.files.processors.JsonExtractor$Processor.lambda$process$0(JsonExtractor.java:70)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
    at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at io.annot8.components.files.processors.JsonExtractor$Processor.process(JsonExtractor.java:65)
    at io.annot8.implementations.pipeline.SimplePipeline.process(SimplePipeline.java:122)
    at java.util.Optional.ifPresent(Optional.java:183)
    at io.annot8.implementations.pipeline.InMemoryPipelineRunner.lambda$run$4(InMemoryPipelineRunner.java:96)
    at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160)
    at io.annot8.implementations.pipeline.InMemoryPipelineRunner.run(InMemoryPipelineRunner.java:96)
    at java.lang.Thread.run(Thread.java:834)`

This have been tested with various .json files, down to very simple (3 field) jsons.

Does anyone have any idea why this might be? There are a couple of tickets (e.g. #27 ) that look a little similar, but none look to have been merged to master (and I can't see that they're related)

**Comment by jamesdbaker** [comment]
I've tried to recreate this error this morning, but haven't been able to. I've used Ubuntu 20.04.2 LTS and the following pipeline:

```
{
   "name":"Issue 43",
   "description":"Test and fix Issue #43",
   "sources":[
      {
         "io.annot8.components.files.sources.FileSystemSource":{
            "name":"File System Source",
            "settings":{
               "rootFolder":"./test",
               "watching":true,
               "recursive":true,
               "reprocessOnModify":true,
               "acceptedFileNamePatterns":[],
            }
         }
      }
   ],
   "processors":[
      {
         "io.annot8.components.files.processors.JsonExtractor":{
            "name":"JSON File Extractor",
            "settings":{
               "removeSourceContent":true,
               "contentFields":[
                  "content"
               ],
               "jsonExtension":[
                  "json"
               ],
               "jsonlExtension":[
                  "jsonl"
               ]
            }
         }
      },
      {
         "io.annot8.components.cyber.processors.Email":{
            "name":"E-mail"
         }
      },
      {
         "io.annot8.components.print.processors.PrintSpans":{
            "name":"Print Spans",
            "settings":{
               "logOutput":true,
               "logLevel":"INFO"
            }
         }
      }
   ]
}
```

I tested with both the commit and Baleen version you stated, and a newer (unreleased) development version of the components and in both cases it worked fine. Looking at the code, I can't see any obvious reason why the two would be treated differently, unless they are fundamentally different on the file system somehow perhaps.

Is that the whole exception? It doesn't seem to show the root exception (i.e. it's missing some stuff at the top) that might help explain what's going on.

I don't think it's related to the other tickets (some of which probably need closing - I'll take a look at that)

**Comment by mattplindsay** [comment]
Thanks James, appreciate the looking into it. I have also investigated further in case it was something to do with the way docker virtualises the filesystem, but it failed on my local (Ubuntu 20.04) as well. 

1) Can I confirm you used the bash 'cp' command to drop a JSON into a monitored folder
2) I took the error from the log display in Baleen3. Is there a better place to get a more full stack trace?

Many thanks for looking into this.

**Comment by mattplindsay** [comment]
Sorry, one further question... Why does your monitored folder commence with a period? Is it relative? That's the only difference I can see to my setup (but will try your pipeline as soon as am at a terminal).

**Comment by jamesdbaker** [comment]
1) I tried dragging/dropping and `cp`-ing, it didn't seem to make a difference.
2) It looks like the log display isn't showing enough lines (I'll look into that) - is there something in the console from which you're running Baleen from? Alternatively, try increasing the log lines in the Baleen 3 web display and see if that shows something more.
3) Yes, the dot just makes it relative to the directory that Baleen is running from, but I've just checked with an absolute path too with no difference.

**Comment by mattplindsay** [comment]
Thanks James. Am still getting the issue, with both a local and a docker version of the build. Am about to try a few further ideas for debugging.

I captured what I think is the full stack trace, as well as noticing an odd behaviour - it seems to think it's processing it twice. I get Two of the errors shown below and the items count in the baleen dash increments twice.

I'll keep going and see if I can turn up anything further. If you have any other clever ideas for debugging, i'd be all ears!

Thanks again.

`2021-04-02 13:20:50.381  INFO 65049 --- [       Thread-4] i.a.i.pipeline.InMemoryPipelineRunner    : Pipeline Issue 43 started
2021-04-02 13:21:23.392 ERROR 65049 --- [       Thread-4] i.a.c.f.p.JsonExtractor$Processor        : Unable to process JSON file

java.nio.file.NoSuchFileException: basic_item.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[na:na]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[na:na]
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[na:na]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371) ~[na:na]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422) ~[na:na]
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3206) ~[na:na]
	at java.base/java.nio.file.Files.readString(Files.java:3284) ~[na:na]
	at io.annot8.components.files.processors.JsonExtractor$Processor.processJson(JsonExtractor.java:108) ~[annot8-components-files-1.1.0-plugin.jar:na]
	at io.annot8.components.files.processors.JsonExtractor$Processor.lambda$process$0(JsonExtractor.java:70) ~[annot8-components-files-1.1.0-plugin.jar:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at io.annot8.components.files.processors.JsonExtractor$Processor.process(JsonExtractor.java:65) ~[annot8-components-files-1.1.0-plugin.jar:na]
	at io.annot8.implementations.pipeline.SimplePipeline.process(SimplePipeline.java:122) ~[annot8-pipeline-implementation-1.0.2.jar!/:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]
	at io.annot8.implementations.pipeline.InMemoryPipelineRunner.lambda$run$4(InMemoryPipelineRunner.java:96) ~[annot8-pipeline-implementation-1.0.2.jar!/:na]
	at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160) ~[annot8-components-annotations-1.1.0-plugin.jar:1.6.3]
	at io.annot8.implementations.pipeline.InMemoryPipelineRunner.run(InMemoryPipelineRunner.java:96) ~[annot8-pipeline-implementation-1.0.2.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
`

**Comment by mattplindsay** [comment]
Btw, given that it's java.nio.file.NoSuchFileException, I'll assume it's something to do with passing the location of the file from the watcher to the JSON extractor. Is there any debug code I can put either into the folder watcher or into the JSON extractor to see what's going on? The strange behaviour I'm seeing (to recap) is:

> Works if pipeline initialises and the folder has content. Those files process fine.

> Doesn't work when files are added (error above).

> When it fails, it processes twice (both failures).

I have tried in both docker environments and local, using pre-compiled annot8 and baleen as well as built from source.

**Comment by mattplindsay** [comment]
James - thanks so much for the help. I have managed to create a docker file and instructions that re-create this issue. Unfortunately one of the jars it more than 100Mb so I cannot upload it here, but have put it into an open folder here:

https://drive.google.com/drive/folders/1y4_6CO_tZE9JFDGBgnAzL0zOJWnKG9hM?usp=sharing

The readme should provide all the details. It would be wonderful if anyone was able to recreate this for me,

**Comment by mattplindsay** [comment]
> 1. I tried dragging/dropping and `cp`-ing, it didn't seem to make a difference.
> 2. It looks like the log display isn't showing enough lines (I'll look into that) - is there something in the console from which you're running Baleen from? Alternatively, try increasing the log lines in the Baleen 3 web display and see if that shows something more.
> 3. Yes, the dot just makes it relative to the directory that Baleen is running from, but I've just checked with an absolute path too with no difference.

Just a thought (and I've just almost ended myself messing around trying to build a docker image with Oracle 11 Java on it (certainly not for the feint hearted!) - Which version of Java are you running? Java 11 OpenJDK?

**Comment by jamesdbaker** [comment]
Thanks @mattplindsay, I was able to recreate the issue with that Docker image and I think I know what's going on: Baleen is picking up the modified file and trying to process it whilst it's still copying, and as such can't read it.

Thinking back, I have seen this happen with larger files in the past, but not with small files. Perhaps the Oracle JDK code is picking up the modified file quicker than the OpenJDK I use does, or perhaps Docker is slowing down the copy command

I've actually already got some stuff in newer development versions that allows you to introduce a delay into FileSystemSource processor to prevent exactly this, so it should be fixed when we next release (I've tested a development version in your Docker container and it works).

In the meantime, you could try adding a `Thread.sleep` call (you may need to experiment with how many milliseconds) into the `createItem` function of `AbstractFileSystemSource` and see if that helps? In the new development version it actually runs this function after a customisable delay on a separate thread (to avoid slowing things down as much), but the above is probably easier to insert.

```
protected boolean createItem(ItemFactory itemFactory, Path path) {
    boolean include = false;

    try{
        Thread.sleep(500); //TODO: See what works for your setup in terms of the delay
    } catch (InterruptedException e) {
        // Do nothing
    }

    ...
```

**Comment by mattplindsay** [comment]
Thanks v much James - appreciate the effort. I thought it might have been a delay issue too, however have tested this, with two (unfortunate) results:
1) I added the sleep into the `AbstractFileSystemSource` and rebuilt and re-deployed.... but the error still occurs. I tried it with a range of different delays (up to 10s) and exactly the same error exists. This was on a local deployment (Unbuntu 20) to rule out any issues with it being the Docker file abstraction subsystem causing issues.

2) I built and deployed the same docker setup (i.e. using `FROM store/oracle/jdk:11`) but the same issue occurs - suggesting it's not down to differences between OpenJDK and Oracle.

Were there any other changes in your development branch, either in the annot8-files component or in dependencies? Did you have success on Baleen 3.0.2?

I'll keep trying to get to the bottom of it - I was wondering if there was a repo or branch of the development version I could try and see if it fixes the issue when I run it here?
(p.s. was going to PR the delay in the `AbstractFileSystemSource` but didn't seem like a lot of value in me doing that....

**Comment by mattplindsay** [comment]
OK, got a much clearer idea of what's going on now:
When the pipeline is started, the `content.getData().toPath()` returns the full path (in my case: /workspace/processing-ready/basic_item.json )
When the pipeline picks up a changed or added file, it only returns the filename (in my case: basic_item.json).

To recreate:

1. Add `log().info("The content.getdata.topath is " + content.getData().toPath());`  into `private boolean processJson(FileContent content) {...` (around line 108)
2. Add a file into the folder
3. Copy a file into the folder.

The following output occurs:

```
2021-04-06T19:45:36.575138 INFO    io.annot8.components.files.processors.JsonExtractor$Processor The content.getdata.topath is /workspace/processing-ready/basic_item.json 
2021-04-06T19:47:35.655226 INFO    io.annot8.components.files.processors.JsonExtractor$Processor The content.getdata.topath is basic_item.json 
2021-04-06T19:47:35.6574 ERROR io.annot8.components.files.processors.JsonExtractor$Processor Unable to process JSON file 
 
  basic_item.json
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    [...]
```
From a bit of a look, I think this might be an issue in the `FileSystemSource.java` as it seems to treat initialFiles somewhat differently when populating the path. A little testing suggests that if the path is a subdirectory of the location that baleen is being run in (i.e. something like `./input`) it processes the file (although still processes if twice (for some odd reason)

**Comment by jbaker-dstl** [comment]
Does making the following change to L148 in FileSystemSource fix it?

```
      WatchKey key;
      while ((key = watchService.poll()) != null) {
        Path dir = (Path) key.watchable();

        for (WatchEvent<?> event : key.pollEvents()) {
          if (createItem(itemFactory, dir.resolve(((WatchEvent<Path>) event).context()))) {

```

The processing twice issue is because the OS sends a CREATE and then one or more MODIFY events on a copy. A workaround is to disable "Reprocess on Modify" unless that's a feature you need. Again, this has been fixed in the new version of this component, which I've rewritten completely and will hopefully be able to release soon.

**Comment by jamesdbaker** [comment]
Does making the following change to L148 in FileSystemSource fix it?

```
      WatchKey key;
      while ((key = watchService.poll()) != null) {
        Path dir = (Path) key.watchable();

        for (WatchEvent<?> event : key.pollEvents()) {
          if (createItem(itemFactory, dir.resolve(((WatchEvent<Path>) event).context()))) {
```

The processing twice issue is because the OS sends a CREATE and then one or more MODIFY events on a copy. A workaround is to disable "Reprocess on Modify" unless that's a feature you need. Again, this has been fixed in the new version of this component, which I've rewritten completely and will hopefully be able to release soon.

**Comment by mattplindsay** [comment]
Great stuff - this works really well thank you!

Do you want me to create a PR for this change? Seems to work really well. Many thanks

**Comment by jamesdbaker** [comment]
Feel free to submit a PR if you want - I guess it will prevent others hitting the same issue until I'm able to push the rewritten version.
